server:
  port: 3000

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootzjh@
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
#  password: 1234

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
  
#配置拦截器白名单 spzx:auth: noAuthUrl: 这三个名称都是随便起的
#注意第一级要顶格写
spzx:
  auth:
    noAuthUrl:
     - /admin/system/index/generateValidateCode
     - /admin/system/index/Login
     - /doc.html
     - /v3/**
     - /webjars/**

  minio:
      endpointUrl: http://127.0.0.1:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucketName: spzx-bucket
logging:
  level:
    com.atguigu.spzx.manager.mapper: DEBUG  # 替换成你的 Mapper 包路径
    org.apache.ibatis: TRACE   # 可选，显示更详细的 SQL 日志
    org.mybatis.spring: TRACE  # 可选
